# Generated by Django 2.2.6 on 2019-10-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_auto_20191011_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='schooling',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
