# Generated by Django 2.2.6 on 2019-10-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_member_schooling'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
            ],
        ),
    ]
