# Generated by Django 2.2.6 on 2019-10-15 15:36

import Member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_testdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=Member.models.upload_image_path),
        ),
    ]
