# Generated by Django 2.2.6 on 2019-10-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_auto_20191015_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
